region: ""
cluster: k6-fargate-cloudwatch-K6Cluster0D119836-9iEp18KLGiLA
service: ""
service_definition: ""
task_definition: ecs-task-def.json
timeout: "10m0s"
run:
  # ... (count, task-definition, overrides など) ...
  # ネットワーク設定 (VPC, Subnet, SG)
  networkConfiguration:
    awsvpcConfiguration:
      # タスクを配置するサブネットIDのリスト
      subnets:
        - "subnet-0123456789abcdef0"
        - "subnet-fedcba9876543210f"

      # タスクに割り当てるセキュリティグループIDのリスト
      securityGroups:
        - "sg-a1b2c3d4e5f6a7b8c"

      # パブリックIPの自動割り当て (Fargateなどで必要に応じて)
      # ENABLED または DISABLED を指定
      assignPublicIp: "DISABLED"
